name: validate-content 
run-name: ${{ github.actor }} is validating content
on: [push, pull_request]
jobs:
  lint-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint script
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/lint.sh
  compile-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run compile script
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/compile.sh

      